name: CI/CD Pipeline

on:
  release:
    types: [published]

env:
  TAG: ${{ github.ref_name }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            VERSION=${{ env.TAG }}
          push: true
          tags: |
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:${{ env.TAG }}
            ${{ vars.DOCKER_HUB_USERNAME }}/hello-world:latest

  pull-and-deploy:
    name: Pull and Deploy to Setonix
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.PAWSEY_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Setonix to known hosts
        run: ssh-keyscan -H setonix.pawsey.org.au >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Execute remote deployment
        run: |
          ansible-playbook -i inventory.ini deploy.yml --extra-vars "version=${{ env.TAG }}"
